name: eco_trash
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  timeago: ^3.7.0
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.4.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  quickalert: ^1.1.0
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/qd.png
     - assets/maheez.png
     - assets/Chair.jpg
     - assets/sofa.jpg
     - assets/Fan.jpg
     - assets/Table.jpg
     - assets/Recycle.png
     - assets/login1.JPG
     - assets/login2.JPG
     - assets/login3.JPG


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
